'use strict';
const FIL = {
    'Home': 'Home', 'Schedules': 'Iskedyul', 'Fleet': 'Mga Bus', 'Live Status': 'Live Status', 'Cargo': 'Padala', 'Help': 'Tulong',
    'My Trips': 'Mga Biyahe Ko', 'Schedules & Fares': 'Iskedyul at Pamasahe', 'Cargo & Parcels': 'Kargamento at Padala',
    'Help & Travel Info': 'Tulong at Impormasyon', 'Find a Booking': 'Hanapin ang Booking', 'Find Booking': 'Hanapin',
    'Sign In': 'Mag-sign In', 'Account': 'Account', 'Book': 'Mag-book', 'Trips': 'Biyahe', 'Track': 'Subaybay',
    'Travel advisory:': 'Abiso sa biyahe:', 'Details': 'Detalye',
    'Road works along Andaya Highway (Quezon) may add 30 to 45 minutes to night trips this week.': 'May ginagawang kalsada sa Andaya Highway (Quezon); maaaring madagdagan ng 30 hanggang 45 minuto ang mga biyaheng panggabi ngayong linggo.',
    'Your Journey to Bicol Starts Here.': 'Dito Nagsisimula ang Biyahe Mo Pa-Bicol.',
    'Secure. Comfortable. Online. Book your provincial travel instantly and pay securely with GCash, Maya, or QR Ph.': 'Ligtas. Komportable. Online. Mag-book agad ng biyahe sa probinsya at magbayad gamit ang GCash, Maya, o QR Ph.',
    'Book Your Trip': 'I-book ang Biyahe Mo', 'One Way': 'One Way', 'Round Trip': 'Balikan',
    'Origin': 'Pinagmulan', 'Destination': 'Patutunguhan', 'Departure Date': 'Petsa ng Alis', 'Return Date': 'Petsa ng Balik',
    'Passengers': 'Mga Pasahero', 'Search Buses': 'Maghanap ng Bus', 'Featured Routes': 'Mga Pangunahing Ruta',
    'All schedules': 'Lahat ng iskedyul', 'Starting at': 'Mula sa', 'First Class from': 'First Class mula sa', 'View Schedule': 'Tingnan ang Iskedyul',
    'Modify Search': 'Baguhin ang Paghahanap', 'All': 'Lahat', 'Select Seats': 'Pumili ng Upuan', 'Booking Closed': 'Sarado na ang Booking', 'Sold Out': 'Ubos Na',
    'Departure': 'Alis', 'Arrival': 'Dating', 'Direct Route': 'Diretsong Biyahe',
    'Step 1 of 2 · Choose your outbound trip': 'Hakbang 1 ng 2 · Piliin ang biyaheng paalis',
    'Step 2 of 2 · Choose your return trip': 'Hakbang 2 ng 2 · Piliin ang biyaheng pabalik',
    'Secure Checkout': 'Ligtas na Pagbabayad', 'Your seats are held for': 'Naka-hold ang upuan mo sa loob ng',
    'Passenger Details': 'Detalye ng Pasahero', 'Log In to Autofill': 'Mag-log In para Mapunan',
    'Senior citizens, PWDs and students get 20% off the fare. Bring the valid ID for each discounted passenger; it is checked at boarding.': 'May 20% diskwento sa pamasahe ang senior citizen, PWD at estudyante. Dalhin ang valid ID ng bawat may diskwento; titingnan ito bago sumakay.',
    'Mobile Number (For E-Ticket)': 'Mobile Number (Para sa E-Ticket)', 'Email Address (Optional)': 'Email (Opsyonal)',
    'Promo Code': 'Promo Code', 'Points': 'Puntos', 'Apply': 'Gamitin', 'Select Payment Method': 'Pumili ng Paraan ng Bayad',
    'Fare Rules': 'Mga Patakaran sa Pamasahe', 'Booking Summary': 'Buod ng Booking', 'Grand Total': 'Kabuuang Bayad', 'Pay Securely': 'Magbayad nang Ligtas',
    'Save as PDF': 'I-save bilang PDF', 'Add to Calendar': 'Idagdag sa Kalendaryo', 'Share': 'Ibahagi', 'Book Another Trip': 'Mag-book Muli',
    'My Parcels': 'Mga Padala Ko', 'Daily departures. Fares are per passenger, before the ₱30 terminal fee.': 'Araw-araw ang mga biyahe. Bawat pasahero ang pamasahe, hindi pa kasama ang ₱30 terminal fee.',
    'Boarding at': 'Sasakay sa', 'Direction': 'Direksyon', 'Live Bus Tracking': 'Live na Pagsubaybay ng Bus', 'GPS-synced arrivals and departures.': 'Mga dating at alis na naka-sync sa GPS.',
    "Send a parcel on tonight's bus. Drop it at the terminal counter, the receiver picks it up at the destination terminal.": 'Magpadala ng parcel sa bus ngayong gabi. Iwan sa counter ng terminal, at kukunin ng tatanggap sa terminal ng destinasyon.',
    'Drop-off terminal': 'Terminal na pagdadalhan', 'Pick-up terminal': 'Terminal na pagkukunan', 'Weight (kg)': 'Timbang (kg)', 'Declared value (₱, optional)': 'Halaga (₱, opsyonal)',
    'Contents': 'Laman', 'Sender name': 'Pangalan ng nagpadala', 'Sender mobile': 'Mobile ng nagpadala', 'Receiver name': 'Pangalan ng tatanggap', 'Receiver mobile': 'Mobile ng tatanggap',
    'Book Drop-off': 'I-book ang Padala', 'Your quote': 'Tantiyang bayad', 'Travel advisories': 'Mga abiso sa biyahe', 'Terminals': 'Mga Terminal',
    'Baggage': 'Bagahe', 'Pets': 'Mga Alagang Hayop', 'Contact us': 'Makipag-ugnayan', 'Select Your Seats': 'Piliin ang Upuan Mo',
    'Outbound': 'Paalis', 'Return': 'Pabalik', 'View Ticket': 'Tingnan ang Ticket', 'Rebook': 'I-rebook', 'Cancel': 'Kanselahin',
    'Upcoming': 'Paparating', 'Completed': 'Tapos Na', 'Cancelled': 'Kinansela', 'Language': 'Wika', 'Install App': 'I-install ang App',
    'Sign Out': 'Mag-sign Out', 'Save': 'I-save', 'Proceed': 'Magpatuloy', 'Choose return': 'Piliin ang pabalik'
};

// Everything else on screen. Keys are the English text exactly as rendered (spaces collapsed).
Object.assign(FIL, {
    // navigation, labels for assistive tech
    'Skip to content': 'Lumaktaw sa nilalaman', 'Main': 'Pangunahin', 'Notifications': 'Mga Abiso', 'Switch language': 'Palitan ang wika', 'Menu': 'Menu',
    'Sign In / Register': 'Mag-sign In / Magrehistro', 'Dismiss': 'Isara', 'Trip type': 'Uri ng biyahe', 'App sections': 'Mga bahagi ng app', 'Close': 'Isara',
    'Back to results': 'Bumalik sa mga resulta', 'Back to operator console': 'Bumalik sa operator console', 'Promo code': 'Promo code', 'Mobile number': 'Mobile number',
    'Search by bus number or route': 'Maghanap ayon sa numero ng bus o ruta', 'Bus no. or route': 'Numero ng bus o ruta', 'e.g. documents, clothes, pili nuts': 'hal. dokumento, damit, pili nuts',
    '11-digit mobile number starting with 09': '11-digit na mobile number na nagsisimula sa 09', 'e.g. BICOL10': 'hal. BICOL10',
    'Language set to English': 'Filipino na ang wika',

    // home
    'PREMIUM 2+1 RECLINING COACHES': 'PREMIUM NA 2+1 RECLINING COACH', 'Select Destination': 'Pumili ng Patutunguhan',
    'Going to Bicol. Tap to switch to Manila-bound': 'Papuntang Bicol. Pindutin para gawing papuntang Manila',
    'Going to Manila. Tap to switch to Bicol-bound': 'Papuntang Manila. Pindutin para gawing papuntang Bicol',
    'Real-time Seat Selection': 'Pagpili ng Upuan, Real-time', 'Pick your exact preferred seat instantly.': 'Piliin agad ang mismong upuang gusto mo.',
    'Instant GCash/Maya': 'Agarang GCash/Maya', 'Secure, 100% cashless local payments.': 'Ligtas at 100% cashless na bayad.',
    'E-Ticket to Your Mobile': 'E-Ticket sa Mobile Mo', 'No printing needed. Scan & board.': 'Hindi na kailangang i-print. I-scan at sumakay.',
    'Manila to Daet': 'Manila papuntang Daet', 'Manila to Naga': 'Manila papuntang Naga', 'Manila to J. Panganiban': 'Manila papuntang J. Panganiban',
    'via Andaya Highway': 'dadaan sa Andaya Highway', 'Premium Lazyboy Recliners': 'Premium na Lazyboy Recliner', 'Direct Terminal Stop': 'Diretso sa Terminal',
    'Experience Unmatched Comfort: Our Fleet': 'Walang Kapantay na Ginhawa: Ang Aming mga Bus',
    'Choose between our luxurious First Class reclining cabins or our efficient and comfortable Standard coaches.': 'Pumili sa marangyang First Class na may reclining na upuan o sa matipid at komportableng Standard coach.',
    'First Class 2+1 Interior': 'Loob ng First Class 2+1', 'Standard 2+2 Interior': 'Loob ng Standard 2+2',
    'Spacious reclining leather armchairs, individual amenities and an onboard restroom.': 'Maluluwag na leather na upuang naihihiga, sariling amenities at CR sa loob ng bus.',
    'Clean, efficient and comfortable, with full air-conditioning and panoramic windows.': 'Malinis, matipid at komportable, fully airconditioned at may malalaking bintana.',
    'Recliner': 'Recliner', 'Aircon': 'Aircon', 'Reclining': 'Naihihiga', '20 kg bag': '20 kg na bagahe', 'Video': 'Video',
    'Why Choose Biyahe Bicol?': 'Bakit Biyahe Bicol?',
    'Connecting Metro Manila to the heart of Bicol, built around your comfort.': 'Nag-uugnay sa Metro Manila at sa puso ng Bicol, para sa ginhawa mo.',
    'Safety & Reliability': 'Ligtas at Maaasahan', 'Rigorous maintenance schedules, speed limiters, and highly trained drivers ensure you arrive safely.': 'Mahigpit na maintenance, speed limiter, at mga sanay na drayber para ligtas kang makarating.',
    'Premium Comfort': 'Premium na Ginhawa', 'Leather recliners, AC, and clean onboard restrooms for our First Class passengers.': 'Leather recliner, aircon, at malinis na CR sa bus para sa mga pasahero ng First Class.',
    '24/7 Support': 'Suporta 24/7', 'Round-the-clock customer service hotlines and terminal support staff.': 'Bukas buong araw at gabi ang hotline at mga tauhan sa terminal.',
    'Customer Testimonials': 'Sabi ng mga Pasahero',
    '"Best sleep I\'ve had on a provincial bus. The First Class 2+1 recliners are spacious and worth every single peso."': '"Pinakamasarap na tulog ko sa provincial bus. Maluwag ang First Class 2+1 recliner at sulit ang bawat piso."',
    '"Smooth booking with GCash. No more long lines at the PITX terminal, and the QR code scanning is so fast!"': '"Madali ang pag-book gamit ang GCash. Wala nang mahabang pila sa PITX, at ang bilis ng pag-scan ng QR code!"',
    '"Biyahe Bicol is always on time. Love the new live tracking board feature on the website to check arrivals."': '"Laging nasa oras ang Biyahe Bicol. Gusto ko ang bagong live tracking sa website para makita ang dating ng bus."',
    'Frequent Traveler, Bicol': 'Madalas Bumiyahe, Bicol', 'First Class': 'First Class', 'Standard': 'Standard',

    // results, seats
    'Fully airconditioned': 'Fully airconditioned', 'CR, USB, Wi-Fi': 'CR, USB, Wi-Fi', 'Sold out': 'Ubos na', 'Departed or boarding': 'Nakaalis na o sumasakay na',
    'Try the next day': 'Subukan ang susunod na araw', 'Seat Legend': 'Gabay sa Upuan', 'Available': 'Bakante', 'Selected': 'Napili', 'Door (+₱50)': 'Malapit sa pinto (+₱50)',
    'Occupied': 'May nakaupo', 'Select exactly': 'Pumili ng eksaktong', 'seat(s). Front seats by the door have extra legroom and a ₱50 surcharge.': 'upuan. Mas maluwag ang mga upuan sa unahan malapit sa pinto at may dagdag na ₱50.',
    'Front / Driver': 'Unahan / Drayber', 'Selected:': 'Napili:', 'None': 'Wala',
    'Outbound seats saved. Now choose your return trip.': 'Na-save ang upuan sa biyaheng paalis. Piliin naman ang biyaheng pabalik.',
    'Pick a departure date from today onward.': 'Pumili ng petsa ng alis mula ngayong araw.', 'The return date cannot be before the departure date.': 'Hindi puwedeng mauna ang petsa ng balik sa petsa ng alis.',

    // checkout
    'Data Privacy & Consent': 'Data Privacy at Pahintulot',
    'I agree to the Terms of Service and Fare Rules, and consent to the processing of my data in compliance with the Philippine Data Privacy Act (RA 10173).': 'Sumasang-ayon ako sa Terms of Service at mga Patakaran sa Pamasahe, at pumapayag sa pagproseso ng aking data alinsunod sa Data Privacy Act (RA 10173).',
    'Send me promo codes and route updates via SMS/Viber.': 'Padalhan ako ng promo code at balita sa ruta sa SMS/Viber.',
    'Fare type': 'Uri ng pamasahe', 'Regular': 'Regular', 'Senior Citizen (20% off)': 'Senior Citizen (20% diskwento)', 'PWD (20% off)': 'PWD (20% diskwento)', 'Student (20% off)': 'Estudyante (20% diskwento)',
    'Seat': 'Upuan', 'Outbound seat': 'Upuan paalis', 'Return seat': 'Upuan pabalik', 'Seats': 'Mga upuan',
    'Add-ons': 'Mga Dagdag', 'Extra baggage': 'Dagdag na bagahe', '20 kg per passenger is free. Add more at ₱150 per 10 kg, per trip.': 'Libre ang 20 kg bawat pasahero. Dagdag na ₱150 bawat 10 kg, bawat biyahe.',
    'Bring a pet': 'Magdala ng alagang hayop', '· ₱150 per trip': '· ₱150 bawat biyahe', 'Travel insurance': 'Travel insurance', '· ₱40 per passenger, per trip': '· ₱40 bawat pasahero, bawat biyahe',
    'Covers accident and lost baggage for the trip.': 'Sakop ang aksidente at nawalang bagahe sa biyahe.',
    'Small cat or dog up to 10 kg, in a closed carrier at your feet.': 'Maliit na pusa o aso hanggang 10 kg, nasa saradong carrier sa may paanan mo.',
    'Pets ride on Standard coaches only, so this is off for a First Class trip.': 'Sa Standard coach lang puwede ang alaga, kaya hindi ito magagamit sa biyaheng First Class.',
    'INSTANT': 'AGARAN', 'Reference: SL-': 'Reference: SL-', 'PENDING': 'HINIHINTAY',
    'Rebooking is allowed up to 4 hours before departure, for a fee of ₱100 per passenger.': 'Puwedeng mag-rebook hanggang 4 na oras bago umalis, sa bayad na ₱100 bawat pasahero.',
    'Cancellation 24 hours or more before departure: 80% refund. Between 24 and 4 hours: 50% refund. Within 4 hours or after departure: no refund.': 'Pagkansela 24 oras o higit pa bago umalis: 80% refund. Sa pagitan ng 24 at 4 na oras: 50% refund. Sa loob ng 4 na oras o pagkaalis: walang refund.',
    'Refunds go back to the original payment method within 3 to 5 banking days.': 'Ibinabalik ang refund sa ginamit na paraan ng bayad sa loob ng 3 hanggang 5 banking day.',
    'Discounted fares need the matching valid ID at boarding, or the fare difference is collected.': 'Kailangan ng tugmang valid ID sa pagsakay ang may diskwento, kung hindi ay sisingilin ang kulang sa pamasahe.',
    'Be at the terminal 30 minutes before departure. Online booking closes 30 minutes before departure.': 'Dumating sa terminal 30 minuto bago umalis. Nagsasara ang online booking 30 minuto bago umalis.',
    'Pet in carrier': 'Alagang hayop sa carrier', 'Terminal fee': 'Terminal fee',
    'Sign in before paying to earn points on this booking.': 'Mag-sign in bago magbayad para makakuha ng puntos sa booking na ito.',
    'That code is not valid or has expired.': 'Hindi valid o expired na ang code na iyan.', 'Your seat hold ran out. Please choose your seats again.': 'Tapos na ang hold sa upuan mo. Pumili ulit ng upuan.',
    'Searching Routes': 'Naghahanap ng Biyahe', 'Fetching real-time availability...': 'Kinukuha ang mga bakanteng upuan...', 'Processing Payment': 'Pinoproseso ang Bayad', 'Connecting to gateway securely...': 'Ligtas na kumokonekta sa gateway...',

    // ticket
    'Payment Successful!': 'Matagumpay ang Bayad!', 'Official E-Ticket Boarding Pass': 'Opisyal na E-Ticket Boarding Pass', 'Booking Ref': 'Booking Ref', 'Passenger(s)': 'Pasahero',
    'Scan at turnstile & door': 'I-scan sa turnstile at pinto', 'Paid via': 'Binayaran gamit ang', 'Total:': 'Kabuuan:', 'Date': 'Petsa', 'Bus': 'Bus',
    'Senior': 'Senior', 'Student': 'Estudyante', 'PWD': 'PWD', 'Travel Insurance': 'Travel Insurance',
    'Booking Found': 'Nahanap ang Booking', 'Here is your e-ticket. Show the QR code at the terminal.': 'Narito ang e-ticket mo. Ipakita ang QR code sa terminal.',
    'Your E-Ticket': 'Ang E-Ticket Mo', 'Booking Cancelled': 'Kinansela ang Booking', 'Show the QR code at the turnstile and at the bus door.': 'Ipakita ang QR code sa turnstile at sa pinto ng bus.',
    'This ticket is saved on this device and opens offline in My Trips.': 'Naka-save ang ticket sa device na ito at mabubuksan kahit walang signal sa Mga Biyahe Ko.',
    'This ticket is saved in My Trips on this device.': 'Naka-save ang ticket sa Mga Biyahe Ko sa device na ito.',
    'QR code needs a connection the first time.': 'Kailangan ng koneksyon ang QR code sa unang beses.', 'Copy Details': 'Kopyahin ang Detalye',
    'Retrieve E-Ticket': 'Kunin ang E-Ticket', 'Booking Reference': 'Booking Reference', 'Mobile Number Used': 'Ginamit na Mobile Number', 'Find Booking': 'Hanapin',
    'Enter your booking reference and the 11-digit mobile number used.': 'Ilagay ang booking reference at ang 11-digit na mobile number na ginamit.',

    // my trips
    'No trips yet': 'Wala pang biyahe', 'Tickets you book on this device appear here and open without a signal.': 'Dito lalabas ang mga ticket na binook sa device na ito, at mabubuksan kahit walang signal.',
    'Tickets you book on this device appear here.': 'Dito lalabas ang mga ticket na binook sa device na ito.',
    'Calendar': 'Kalendaryo', 'Rebooked': 'Na-rebook', 'Awaiting drop-off': 'Hinihintay na ihatid', 'Which trip': 'Aling biyahe', 'New travel date': 'Bagong petsa ng biyahe',
    'Back': 'Bumalik', 'Keep it': 'Huwag na', 'Confirm': 'Kumpirmahin', 'Keep my trip': 'Ituloy ang biyahe ko', 'Cancel booking': 'Kanselahin ang booking',
    'Choose the new date.': 'Piliin ang bagong petsa.', 'That is the date you already have.': 'Iyan na ang petsa mo ngayon.',
    'That departure has already left or is closing. Pick a later date.': 'Nakaalis na o magsasara na ang biyaheng iyan. Pumili ng mas huling petsa.',
    'The outbound trip has to come before the return trip.': 'Dapat mauna ang biyaheng paalis sa biyaheng pabalik.', 'That bus is full on the new date. Pick another date.': 'Puno na ang bus sa bagong petsa. Pumili ng ibang petsa.',
    'You are 24 hours or more from departure, so the refund is': '24 oras o higit pa bago ang alis, kaya ang refund ay', 'You are less than 24 hours from departure, so the refund is': 'Wala nang 24 oras bago ang alis, kaya ang refund ay',
    'Calendar file saved. Open it to add the trip.': 'Na-save ang calendar file. Buksan para idagdag ang biyahe.', 'Trip details copied. Paste them into any chat.': 'Nakopya ang detalye ng biyahe. I-paste sa kahit anong chat.',
    'Could not share from this browser.': 'Hindi maibahagi mula sa browser na ito.',

    // schedules, live board
    'To Bicol': 'Papuntang Bicol', 'To Manila': 'Papuntang Manila',
    'GPS-synced arrivals and departures. Tap the bell on a bus to be alerted if it runs late.': 'Mga dating at alis na naka-sync sa GPS. Pindutin ang kampana ng bus para maabisuhan kapag naantala ito.',
    'BOARDING': 'SUMASAKAY NA', 'DELAYED': 'ANTALA', 'ON TIME': 'NASA ORAS', 'EARLY': 'MAAGA', 'Bus #': 'Bus #', 'Route': 'Ruta', 'Scheduled': 'Iskedyul', 'Status': 'Status',
    'Current Location': 'Kasalukuyang Lokasyon', 'Alerts': 'Abiso', 'No bus matches that search.': 'Walang bus na tumugma sa hinanap.',

    // cargo
    'The parcel holds no cash, live animals, perishables without packing, flammables or other prohibited items, and may be opened for inspection.': 'Walang lamang pera, buhay na hayop, nabubulok na walang maayos na balot, madaling magliyab o iba pang bawal ang parcel, at maaari itong buksan para inspeksyunin.',
    'Rates': 'Presyo', 'Up to 3 kg': 'Hanggang 3 kg', 'Up to 10 kg': 'Hanggang 10 kg', 'Up to 20 kg': 'Hanggang 20 kg', 'Each kg over 20 (max 50 kg)': 'Bawat kg na lampas sa 20 (hanggang 50 kg)',
    'Insurance': 'Insurance', '1% of declared value': '1% ng idineklarang halaga', 'Insurance (1%)': 'Insurance (1%)',
    'Pay at the counter on drop-off. Cut-off is 1 hour before the bus leaves.': 'Magbayad sa counter pagdala ng parcel. Cut-off ay 1 oras bago umalis ang bus.',
    'Pay at drop-off': 'Babayaran pagdala', 'Choose two different terminals.': 'Pumili ng dalawang magkaibang terminal.', 'The limit is 50 kg per parcel. Split it into two parcels.': '50 kg ang limit bawat parcel. Hatiin sa dalawang parcel.',
    'Drop-off booked': 'Na-book ang padala', '. The receiver gets an SMS when the parcel arrives and shows a valid ID to claim it.': '. Makakatanggap ng SMS ang tatanggap pagdating ng parcel, at magpapakita ng valid ID para makuha ito.',
    'See it in My Trips': 'Tingnan sa Mga Biyahe Ko', 'Check the terminals and the weight first.': 'Tingnan muna ang mga terminal at ang timbang.',

    // help
    'During typhoon signals, trips can be held at the terminal. Check Live Status before leaving home.': 'Kapag may typhoon signal, maaaring pigilan ang biyahe sa terminal. Tingnan ang Live Status bago umalis ng bahay.',
    'Peak dates (Undas, Christmas, Holy Week) sell out early. Book at least a week ahead.': 'Mabilis maubos ang upuan tuwing Undas, Pasko at Semana Santa. Mag-book nang isang linggo man lang bago bumiyahe.',
    'Open 24 hours': 'Bukas 24 oras', 'Open in Maps': 'Buksan sa Maps', 'Boarding stop, 5:00 AM to 12 MN': 'Sakayan lang, 5:00 AM hanggang 12 MN',
    'Free: one checked bag up to 20 kg in the hold, plus one small hand-carry on board.': 'Libre: isang bagahe hanggang 20 kg sa compartment, at isang maliit na hand-carry sa loob.',
    'Excess baggage: ₱20 per kg, paid at the counter. Single pieces over 30 kg travel as cargo.': 'Sobrang bagahe: ₱20 bawat kg, babayaran sa counter. Ang isang pirasong lampas 30 kg ay ituturing na cargo.',
    'Tag every bag with your name and mobile number. Keep cash, gadgets and medicine with you.': 'Lagyan ng pangalan at mobile number ang bawat bagahe. Dalhin sa loob ang pera, gadget at gamot.',
    'Not allowed: flammables, firearms, strong-smelling items such as durian, and unpacked fresh fish.': 'Bawal: madaling magliyab, baril, mababahong bagay gaya ng durian, at sariwang isdang walang balot.',
    'Small cats and dogs (up to 10 kg) are welcome on Standard coaches, in a closed, leak-proof carrier.': 'Puwede sa Standard coach ang maliliit na pusa at aso (hanggang 10 kg), nasa sarado at hindi tumatagas na carrier.',
    'One pet per passenger, ₱150 per trip. The carrier stays at your feet, not on a seat.': 'Isang alaga bawat pasahero, ₱150 bawat biyahe. Sa paanan mo ang carrier, hindi sa upuan.',
    'Bring the vaccination card. The pet should wear a diaper for the whole trip.': 'Dalhin ang vaccination card. Naka-diaper dapat ang alaga sa buong biyahe.',
    'Pets are not carried in First Class cabins or in the baggage hold.': 'Hindi isinasakay ang alaga sa First Class o sa compartment ng bagahe.',
    'How early should I be at the terminal?': 'Gaano kaaga dapat ako sa terminal?',
    'At least 30 minutes before departure. Boarding closes 10 minutes before the bus leaves, and a no-show ticket is forfeited.': 'Hindi bababa sa 30 minuto bago umalis. Nagsasara ang pagsakay 10 minuto bago umalis ang bus, at mawawalan ng bisa ang ticket ng hindi sumipot.',
    'Do I need to print my ticket?': 'Kailangan ko bang i-print ang ticket?',
    'No. Show the QR code from My Trips at the turnstile and again at the bus door. The ticket is saved on your phone and opens without a signal.': 'Hindi. Ipakita ang QR code mula sa Mga Biyahe Ko sa turnstile at muli sa pinto ng bus. Naka-save ang ticket sa phone mo at mabubuksan kahit walang signal.',
    'No. Show the QR code from My Trips at the turnstile and again at the bus door. The ticket stays in My Trips on this device.': 'Hindi. Ipakita ang QR code mula sa Mga Biyahe Ko sa turnstile at muli sa pinto ng bus. Nananatili ang ticket sa Mga Biyahe Ko sa device na ito.',
    'How do senior, PWD and student discounts work?': 'Paano ang diskwento ng senior, PWD at estudyante?',
    'Pick the fare type for each passenger at checkout to get 20% off the fare. Each discounted passenger shows the matching valid ID at boarding, or pays the fare difference.': 'Piliin ang uri ng pamasahe ng bawat pasahero sa checkout para sa 20% diskwento. Magpapakita ng tugmang valid ID sa pagsakay ang bawat may diskwento, o babayaran ang kulang.',
    'Can I change my travel date?': 'Puwede ko bang palitan ang petsa ng biyahe?',
    'Yes, up to 4 hours before departure, for ₱100 per passenger. Open My Trips, tap Rebook and choose the new date. If your seats are taken on the new date you are moved to the nearest free ones.': 'Oo, hanggang 4 na oras bago umalis, sa ₱100 bawat pasahero. Buksan ang Mga Biyahe Ko, pindutin ang I-rebook at piliin ang bagong petsa. Kung may nakaupo na sa upuan mo sa bagong petsa, ililipat ka sa pinakamalapit na bakante.',
    'How do refunds work?': 'Paano ang refund?',
    'Cancel in My Trips. You get 80% back when you cancel 24 hours or more before departure, 50% between 24 and 4 hours, and nothing after that. Refunds reach the original payment method in 3 to 5 banking days.': 'Mag-cancel sa Mga Biyahe Ko. 80% ang ibabalik kapag nag-cancel 24 oras o higit pa bago umalis, 50% sa pagitan ng 24 at 4 na oras, at wala na pagkatapos noon. Darating ang refund sa ginamit na paraan ng bayad sa loob ng 3 hanggang 5 banking day.',
    'What if my trip is cancelled by weather?': 'Paano kung makansela ang biyahe dahil sa panahon?',
    'When the operator cancels a trip, you choose a free rebooking to any date within 30 days or a full refund.': 'Kapag ang kompanya ang nagkansela, pipili ka ng libreng rebooking sa kahit anong petsa sa loob ng 30 araw o buong refund.',
    'Can children ride free?': 'Libre ba ang mga bata?',
    'One child under 3 feet tall rides free on the lap of each paying adult. Children who take a seat pay the full fare.': 'Libre ang isang batang wala pang 3 talampakan ang taas kung kandong ng bawat nagbabayad na matanda. Buong pamasahe ang batang may sariling upuan.',
    'How do loyalty points work?': 'Paano ang loyalty points?',
    'Sign in before paying and you earn 1 point for every ₱20 spent. Each point is worth ₱1 off a later booking.': 'Mag-sign in bago magbayad at makakakuha ka ng 1 puntos sa bawat ₱20. Katumbas ng ₱1 na bawas sa susunod na booking ang bawat puntos.',
    'Chat on Messenger': 'Mag-chat sa Messenger',

    // footer
    'A placeholder bus line for this demo: safe, comfortable and reliable travel between Metro Manila and Bicol.': 'Placeholder na bus line para sa demo na ito: ligtas, komportable at maaasahang biyahe sa pagitan ng Metro Manila at Bicol.',
    'Quick Links': 'Mga Link', 'Book a Ticket': 'Mag-book ng Ticket', 'Live Bus Tracker': 'Live na Pagsubaybay', 'Travel Info': 'Impormasyon sa Biyahe', 'Baggage & Pets': 'Bagahe at Alaga',
    'Our Fleet': 'Ang Aming mga Bus', 'Operator console (staff demo)': 'Operator console (demo para sa staff)', 'Hotlines': 'Mga Hotline', 'Email': 'Email',
    '© 2026 Biyahe Bicol Demo Lines, a placeholder brand.': '© 2026 Biyahe Bicol Demo Lines, isang placeholder na brand.',
    'Terms & Fare Rules': 'Mga Tuntunin at Patakaran sa Pamasahe', 'Data Privacy (RA 10173)': 'Data Privacy (RA 10173)',
    'Prototype demo with a placeholder brand. Schedules, fares, policies, contact details and seats are sample data, and no payment is taken.': 'Prototype demo na may placeholder na brand. Sample lang ang mga iskedyul, pamasahe, patakaran, contact at upuan, at walang kinukuhang bayad.',

    // sign-in, account
    'Welcome': 'Mabuhay', 'Continue': 'Magpatuloy', 'Verify & Log In': 'I-verify at Mag-log In',
    'Enter your mobile number to sign in or create an account instantly via OTP.': 'Ilagay ang mobile number para mag-sign in o gumawa agad ng account gamit ang OTP.',
    'Enter your 10-digit mobile number, e.g. 917 123 4567.': 'Ilagay ang 10-digit na mobile number, hal. 917 123 4567.', 'Enter all 4 digits.': 'Ilagay ang lahat ng 4 na digit.',
    'Sign in with your mobile number': 'Mag-sign in gamit ang mobile number mo', 'Checkout fills itself in, and you earn 1 point for every ₱20 you pay.': 'Kusang mapupunan ang checkout, at may 1 puntos ka sa bawat ₱20 na ibabayad.',
    'Operator console': 'Operator console', 'Staff demo': 'Demo para sa staff', 'English': 'English',
    'iPhone: tap Share, then Add to Home Screen. Android: open the browser menu, then Install app.': 'iPhone: pindutin ang Share, tapos Add to Home Screen. Android: buksan ang menu ng browser, tapos Install app.',
    'Installed. You are using the app.': 'Naka-install na. Ginagamit mo na ang app.', 'Add it to your home screen for one-tap booking and offline tickets.': 'Idagdag sa home screen para sa isang-pindot na booking at ticket kahit offline.',
    'Reset demo data on this device': 'I-reset ang demo data sa device na ito', 'Suki Points': 'Suki Points', 'Your details': 'Ang detalye mo', 'First name': 'Pangalan', 'Last name': 'Apelyido', 'Mobile': 'Mobile',
    'Signed out': 'Naka-sign out na', 'Details saved': 'Na-save ang detalye', 'Demo data cleared': 'Nabura ang demo data', 'App installed': 'Na-install ang app',
    'Reset demo data?': 'I-reset ang demo data?', 'This clears the bookings, parcels, points and sign-in saved on this device.': 'Mabubura ang mga booking, padala, puntos at sign-in na naka-save sa device na ito.', 'Reset': 'I-reset',

    // notifications
    'Clear all': 'Burahin lahat', 'Nothing yet. Trip reminders and delay alerts show up here.': 'Wala pa. Dito lalabas ang paalala sa biyahe at abiso ng pagkaantala.',
    'Booking confirmed': 'Kumpirmado ang booking', 'Trip reminder': 'Paalala sa biyahe', 'Your bus leaves soon': 'Malapit nang umalis ang bus mo'
});

const PLACE = '(PITX Manila|Cubao EDSA|Daet Hub|Turbina, Calamba|PITX|Cubao|Turbina|Daet|Naga|Jose Panganiban|J\\. Panganiban|Pio Duran|Manila)';
// Text with numbers, names or dates in it. First match wins.
const FIL_RX = [
    [/^(\d+) Passengers?$/, '$1 Pasahero'],
    [/^(\d+) passengers?$/, '$1 pasahero'],
    [/^(\d.*[AP]M) to (\d.*(?:[AP]M|MN))$/, '$1 hanggang $2'],
    [new RegExp('^' + PLACE + ' to ' + PLACE + '$'), '$1 papuntang $2'],
    [new RegExp('^(Outbound|Return): ' + PLACE + ' to ' + PLACE + ', (.+)$'), (m, d, a, b, date) => `${d === 'Outbound' ? 'Paalis' : 'Pabalik'}: ${a} papuntang ${b}, ${date}`],
    [/^for (.+)$/, 'para kay $1'],
    [/^(₱[\d,.]+) at drop-off$/, '$1 pagdala'],
    [/^(₱[\d,.]+) per seat$/, '$1 bawat upuan'],
    [/^Almost full \((\d+) left\)$/, 'Halos puno na ($1 na lang)'],
    [/^(\d+) seats left$/, '$1 upuan ang natitira'],
    [/^Only (\d+) seats? left$/, '$1 upuan na lang'],
    [/^Arrival \(\+1d\)$/, 'Dating (+1 araw)'],
    [/^Seats? ([\d, \/]+)$/, 'Upuan $1'],
    [/^Seat (\d+)( occupied)?(, door seat, plus ₱50)?$/, (m, n, occ, door) => `Upuan ${n}${occ ? ', may nakaupo' : ''}${door ? ', malapit sa pinto, dagdag na ₱50' : ''}`],
    [/^Passenger (\d+) full name( \(contact person\))?$/, (m, n, c) => `Buong pangalan ng pasahero ${n}${c ? ' (contact person)' : ''}`],
    [/^Base fare \((\d+) pax( × 2 trips)?\)$/, (m, n, two) => `Pamasahe (${n} pasahero${two ? ' × 2 biyahe' : ''})`],
    [/^Door seat premium \((\d+)×\)$/, 'Dagdag sa upuang malapit sa pinto ($1×)'],
    [/^Terminal fee \(2 trips\)$/, 'Terminal fee (2 biyahe)'],
    [/^Senior \/ PWD \/ Student \((\d+)\)$/, 'Senior / PWD / Estudyante ($1)'],
    [/^Extra baggage \(\+(\d+) kg\)$/, 'Dagdag na bagahe (+$1 kg)'],
    [/^\+(\d+) kg baggage( paid)?$/, (m, n, paid) => `+${n} kg na bagahe${paid ? ', bayad na' : ''}`],
    [/^Travel insurance \((\d+) pax\)$/, 'Travel insurance ($1 pasahero)'],
    [/^Points redeemed \((\d+)\)$/, 'Puntos na ginamit ($1)'],
    [/^You will earn (\d+) points on this booking\.$/, 'Makakakuha ka ng $1 puntos sa booking na ito.'],
    [/^You earned (\d+) points on this booking\.$/, 'Nakakuha ka ng $1 puntos sa booking na ito.'],
    [/^Use my (\d+) points \((₱\d+) off\)$/, 'Gamitin ang $1 puntos ko (bawas na $2)'],
    [/^BICOL10 applied: 10% off fares\.$/, 'Nagamit ang BICOL10: 10% bawas sa pamasahe.'],
    [/^SUPER50 applied: ₱50 off\.$/, 'Nagamit ang SUPER50: ₱50 bawas.'],
    [/^You only need (\d+) seats?\. Tap a selected seat to change it\.$/, '$1 upuan lang ang kailangan mo. Pindutin ang napiling upuan para palitan.'],
    [/^No bookable trips are left on (.+) for (\d+) passengers?\.$/, 'Wala nang mabu-book na biyahe sa $1 para sa $2 pasahero.'],
    [/^Your booking is confirmed\. A copy was sent by SMS to (\d+)\.$/, 'Kumpirmado ang booking mo. May kopyang ipinadala sa SMS sa $1.'],
    [/^Cancelled\. Refund of (₱[\d,.]+) to (.+)\.$/, 'Kinansela. Refund na $1 sa $2.'],
    [/^Refund of (₱[\d,.]+) to (.+), 3 to 5 banking days\.$/, 'Refund na $1 sa $2, 3 hanggang 5 banking day.'],
    [/^Changes close (\d+) hours before departure\.$/, 'Hindi na puwedeng baguhin $1 oras bago umalis.'],
    [/^Rebook (SL-\w+)$/, 'I-rebook ang $1'],
    [/^Cancel (SL-\w+)\?$/, 'Kanselahin ang $1?'],
    [/^Same bus and departure time\. Rebooking fee:$/, 'Parehong bus at oras ng alis. Bayad sa rebooking:'],
    [/^\((₱[\d,.]+) × (\d+)\), charged to (.+)\. If your seats are taken on the new date, you get the nearest free ones\.$/, '($1 × $2), sisingilin sa $3. Kung may nakaupo na sa upuan mo sa bagong petsa, ililipat ka sa pinakamalapit na bakante.'],
    [/^It goes back to (.+) in 3 to 5 banking days\. Your seats are released right away and this cannot be undone\.$/, 'Ibabalik ito sa $1 sa loob ng 3 hanggang 5 banking day. Bibitawan agad ang mga upuan mo at hindi na ito mababawi.'],
    [/^Rebooked to (.+)\. Same seats\.$/, 'Na-rebook sa $1. Parehong upuan.'],
    [/^Rebooked\. Seats moved: (.+)\.$/, 'Na-rebook. Nalipat ang upuan: $1.'],
    [/^Booking cancelled\. (₱[\d,.]+) will be refunded\.$/, 'Kinansela ang booking. $1 ang ire-refund.'],
    [/^No booking matches that reference and mobile number\. \(Demo: try (SL-\w+)\.\)$/, 'Walang booking na tumugma sa reference at mobile number. (Demo: subukan ang $1.)'],
    [/^Enter the 4-digit code sent to \+63 (\d+)\. \(Demo: any 4 digits work\.\)$/, 'Ilagay ang 4-digit na code na ipinadala sa +63 $1. (Demo: kahit anong 4 na digit.)'],
    [/^Signed in as (\d+)$/, 'Naka-sign in bilang $1'],
    [/^Worth (₱[\d,.]+) off your next booking\. Earn 1 point for every ₱20 you pay while signed in\.$/, 'Katumbas ng $1 na bawas sa susunod mong booking. May 1 puntos sa bawat ₱20 na ibabayad habang naka-sign in.'],
    [/^(\d+) upcoming$/, '$1 paparating'],
    [/^Sched (.+)$/, 'Iskedyul $1'],
    [/^Alert me about bus (.+)$/, 'Abisuhan ako tungkol sa bus $1'],
    [/^Stop alerts for bus (.+)$/, 'Ihinto ang abiso sa bus $1'],
    [/^Alerts off for bus (.+)$/, 'Naka-off ang abiso sa bus $1'],
    [/^You will be alerted if bus (.+) is delayed$/, 'Aabisuhan ka kapag naantala ang bus $1'],
    [/^Bus (.+) is delayed$/, 'Naantala ang bus $1'],
    [/^(.+): new time (.+) \(scheduled (.+)\)\.( Your ticket stays valid\.)?$/, (m, r, a, b, v) => `${r}: bagong oras ${a} (iskedyul ${b}).${v ? ' Valid pa rin ang ticket mo.' : ''}`],
    [/^Notifications, (\d+) unread$/, 'Mga abiso, $1 hindi pa nababasa'],
    [/^Freight \(([\d.]+) kg\)$/, 'Bayad sa padala ($1 kg)'],
    [/^Show this code at the (.+) counter and pay$/, 'Ipakita ang code na ito sa counter ng $1 at magbayad ng'],
    [/^Parcel drop-off booked: (.+)$/, 'Na-book ang padala: $1'],
    [new RegExp('^' + PLACE + ' to ' + PLACE + ', bus (.+), leaves at (.+)\\. Be at ' + PLACE + ' 30 minutes early with your QR code and any discount IDs\\.$'), '$1 papuntang $2, bus $3, aalis nang $4. Dumating sa $5 nang 30 minuto bago umalis, dala ang QR code at mga ID para sa diskwento.'],
    [new RegExp('^' + PLACE + ' to ' + PLACE + ' on (.+) at (.+), bus (.+), seats (.+)\\.$'), '$1 papuntang $2 sa $3 nang $4, bus $5, upuan $6.']
];

// tour, sample data, payment screens, route map, saved passengers
Object.assign(FIL, {
    'Take the 2-minute tour': 'Tingnan ang 2-minutong tour', 'Take the guided tour': 'Tingnan ang guided tour', 'Load a sample trip': 'Mag-load ng sample na biyahe',
    'Saved passengers': 'Mga naka-save na pasahero', 'Remove saved passenger': 'Alisin ang naka-save na pasahero',
    'Guided tour ·': 'Guided tour ·', 'Guided tour': 'Guided tour', 'End tour': 'Tapusin ang tour', 'Next': 'Susunod', 'Finish': 'Tapos',
    'Search a trip': 'Maghanap ng biyahe', 'Choose where you board and where you are going. The switch under the two fields reverses the direction, and Round Trip adds a return date.': 'Piliin kung saan ka sasakay at saan ka pupunta. Binabaligtad ng switch sa ilalim ng dalawang field ang direksyon, at nagdadagdag ng petsa ng balik ang Balikan.',
    'Choose a bus': 'Pumili ng bus', 'Each departure shows the class, the fare and the seats left. Booking closes 30 minutes before the bus leaves.': 'Makikita sa bawat biyahe ang klase, pamasahe at natitirang upuan. Nagsasara ang booking 30 minuto bago umalis ang bus.',
    'Pick the exact seat': 'Piliin ang mismong upuan', 'Grey seats are taken. Gold seats by the door have extra legroom for ₱50 more.': 'May nakaupo na sa kulay-abong upuan. Mas maluwag ang gintong upuan malapit sa pinto, dagdag na ₱50.',
    'Passengers, discounts and add-ons': 'Pasahero, diskwento at mga dagdag', 'Every passenger gets a name, a fare type and a seat. Senior, PWD and student fares take 20% off. Extra baggage, a pet and insurance are just below.': 'May pangalan, uri ng pamasahe at upuan ang bawat pasahero. 20% ang bawas sa senior, PWD at estudyante. Nasa ibaba ang dagdag na bagahe, alagang hayop at insurance.',
    'The e-ticket': 'Ang e-ticket', 'A paid ticket carries a signed QR code and stays on the phone, even without a signal.': 'May pirmadong QR code ang bayad na ticket at nananatili ito sa phone kahit walang signal.',
    'Rebook to another date, cancel for a refund, add the trip to a calendar or share it.': 'Mag-rebook sa ibang petsa, mag-cancel para sa refund, idagdag sa kalendaryo o ibahagi ang biyahe.',
    'Live bus tracking': 'Live na pagsubaybay ng bus', 'Buses on the road right now. Tap one for its arrival time, and tap the bell to be alerted if it runs late.': 'Mga bus na nasa biyahe ngayon. Pindutin ang isa para sa oras ng dating, at pindutin ang kampana para maabisuhan kapag naantala.',
    'The operator console': 'Ang operator console', 'What your staff see: every departure, seats sold, revenue, the passenger manifest, counter sales, fares and advisories.': 'Ang nakikita ng staff ninyo: bawat biyahe, nabentang upuan, kita, listahan ng pasahero, benta sa counter, pamasahe at mga abiso.',
    'Boarding at the gate': 'Pagsakay sa gate', 'Staff scan the QR code. A valid ticket boards in one tap, and an edited or reused one is refused.': 'Ini-scan ng staff ang QR code. Isang pindot lang ang valid na ticket, at tinatanggihan ang binago o nagamit na.',
    'That is the tour': 'Iyan ang tour', 'Everything you saw runs on sample data. The language switch at the top changes the whole app to Filipino.': 'Sample data ang lahat ng nakita mo. Ginagawang Filipino ang buong app ng language switch sa itaas.',
    'Sample trip loaded. Open My Trips, the bell, or the operator console.': 'Na-load ang sample na biyahe. Buksan ang Mga Biyahe Ko, ang kampana, o ang operator console.', 'The sample trip is already loaded.': 'Naka-load na ang sample na biyahe.',
    'That passenger is already on this booking.': 'Nasa booking na ito ang pasaherong iyan.', 'Every passenger already has a name. Clear one to swap.': 'May pangalan na ang bawat pasahero. Burahin ang isa para mapalitan.',
    'Amount due': 'Babayaran', 'Wallet number': 'Numero ng wallet', 'You would approve this with your MPIN in the wallet app.': 'Aaprubahan mo ito gamit ang MPIN mo sa wallet app.',
    'Scan with any bank or e-wallet app, then tap the button below.': 'I-scan gamit ang kahit anong bank o e-wallet app, tapos pindutin ang button sa ibaba.',
    'Test card': 'Test card', 'No real card details are asked for in this demo.': 'Walang hinihinging totoong detalye ng card sa demo na ito.', 'I have paid': 'Nakabayad na ako',
    'Simulate a failed payment': 'Subukan ang bigong bayad', 'Card payment': 'Bayad gamit ang card', 'Complete your payment': 'Tapusin ang bayad',
    'Payment did not go through.': 'Hindi natuloy ang bayad.', 'Nothing was charged and your seats are still held. Try again or pick another payment method.': 'Walang nasingil at naka-hold pa ang mga upuan mo. Subukan ulit o pumili ng ibang paraan ng bayad.',
    'Payment did not go through. Nothing was charged.': 'Hindi natuloy ang bayad. Walang nasingil.',
    'On the road now': 'Nasa biyahe ngayon', 'No buses on the road right now': 'Walang bus na nasa biyahe ngayon', 'On schedule': 'Nasa oras', 'Delayed': 'Antala',
    'Tap a bus for its arrival time.': 'Pindutin ang bus para sa oras ng dating.', 'Running 15 minutes late': 'Huli nang 15 minuto', 'Alert me': 'Abisuhan ako', 'Stop alerts': 'Ihinto ang abiso',
    'Travel advisory': 'Abiso sa biyahe'
});
FIL_RX.push(
    [/^Paying (.+)$/, 'Magbabayad sa $1'],
    [/^Pay (₱[\d,.]+)$/, 'Magbayad ng $1'],
    [/^(\d+) bus(?:es)? on the road$/, '$1 bus ang nasa biyahe'],
    [/^arrives (.+)$/, 'darating nang $1']
);
